# Generated by Django 3.0 on 2022-12-08 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='oc_lettings_profile',
        ),
    ]
