# Generated by Django 3.0 on 2022-12-08 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_auto_20221208_1325'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Profile',
                ),
            ],
            # You want to reuse the table, so don't drop it
            database_operations=[],
        )
    ]
